### ISSUE TITLE
Rare problem of outputting negative float numbers

### ISSUE THREAD

**Issue by DmiKarasev** [cesanta/mjson#41] opened 2021-09-03 15:44 UTC
About a year ago I used in my project an old version of mjson which consisted of one header file and a slightly different API. In this version Sergey Lyubka was specified in copyright notice. Everything seemed to work correctly in it.

The project consists in the fact that the board sends data in json format to the server, and I can see the data for the last day in the server logs. I do not know which logger is used on the server (I did not write applications for this server), but I assume that it outputs data in the form in which it came from the board

A few months ago I updated the `mjson` in the project to version 1.2.5. After that, I noticed that sometimes strange telemetry comes from the board. Forming a json string, I am using the API `mjson_printf` as follows:

```
  float v = &data.p;
  ...
  mjson_printf(&mjson_print_fixed_buf, &out, "%Q:\"%g\",", "p", *v++);
  ...
```

I noticed that very rarely and only for negative real numbers that I print using the `%g` specifier, something like this is output:

```
  \"p\":\"-80\u0002.01\",
```

`\uXXXX` can be \u0002, \u0003 or \u0005. This insertion always happens for negative numbers in the integer part and can happen in different variables (not only for "p"). To understand how often this happens, I attach a graph based on telemetry values for a day. Data comes to the server every 5 seconds, I replaced these strange values with `-6666` so that you can see how often they appear.

![image](https://user-images.githubusercontent.com/70858477/132031681-a24067c5-e116-45ca-b37b-ea71c8b71d36.png)

Boards with the old version of mjson do not send such values, but I did not find a place in the mjson library code where such an escape sequence is written to the output json string.

Is it possible for such a sequence to occur when using `mjson_printf()`?

**Comment by cpq** [comment] 2021-09-04 10:54
Please use `double`, not `float`, as per API description in the README.

**Comment by cpq** [comment] 2021-09-04 11:04
What you see, is most probably the result of the - not so recent - refactoring of the mjson code. Before, it used stdlib `snprintf()` to print integers and doubles. Some customers, however, used boards and SDKs were floating point support is missing, therefore mjson did not work as expected.

Thus mjson employed its own [mjson_print_dbl()](https://github.com/cesanta/mjson/blob/ef5d536bb4169069e24e683ba06f4c92d4d18566/src/mjson.c#L561) - and chances are, there is a bug there that causes certain numbers printed incorrectly.

First, please update to the recent code. There was a very recent update that fixed a use case that looks like yours. If that does not help, please use an alternative logging to catch the values that cause issues.

Please feedback when you have more on this.

**Comment by DmiKarasev** [comment] 2021-09-04 11:52
Thanks for your answer, Sergey.

I have already update mjson to version 1.2.7, but the firmware update has not yet reached the clients.

As soon as there is fresh data with version 1.2.7, I will write to you

**Comment by cpq** [comment] 2021-09-04 18:56
@DmiKarasev thank you. Out of curiosity, what is the hardware architecture and toolchain used?

**Comment by DmiKarasev** [comment] 2021-09-04 19:18
I use STM32F405RG (Cortex-M4F) with GCC (in STM32CubeIDE v1.7.0)

**Comment by cpq** [comment] 2021-09-05 05:43
@DmiKarasev thank you.

These questions are irrelevant for this discussion, but somewhat relevant for the related projects we're working on - so please feel free to ignore. If you answer though, I'd appreciate.
1. What is the connectivity hardware - cellular/ethernet/wifi chip used?
2. What is the software - is it https://github.com/cesanta/mongoose by any chance, or it is home-grown on top of Cube's LWIP stack?
3. What is the OTA mechanism - home-grown or some library was used? Have you seen another product of ours, https://vcon.io ?

Thanks!

**Comment by DmiKarasev** [comment] 2021-09-06 08:25
1. I am working on a commercial project and am using a custom board based on STM32F405RG MCU, ESP8266 WiFi module and SIM800C GSM module. Basically, for communication with our MQTT broker, the WiFi channel is used, and the GSM channel is used as a backup and optional. The project uses FreeRTOS on STM32.
2. The entire TCP/IP stack is implemented on ESP8266 and SIM800C modules, so on the STM32 side I send only AT commands
3. We use a custom OTA mechanism that implements the transfer of encrypted firmware via MQTT. Everything is implemented on the board side, but the server backend does not yet support this OTA mechanism. Therefore, the delivery of the update is still difficult.

**Comment by cpq** [comment] 2021-09-16 15:41
@DmiKarasev do you see any issues after the update to HEAD? Or is it gone?

**Comment by DmiKarasev** [comment] 2021-09-16 17:26
Hello, @cpq! My apologies for the long wait...
I have updated the firmware from mjson v1.2.7 to two clients as a test. I have not yet replaced float with double due to memory savings (i have a lot of float variables in fw). At the same time, the client, which had the firmware with mjson v1.2.5, still remained on the same version. There are 28 boards in total on the server, i.e. on 25 boards there is a very old mjson, which I talked about in the description of the problem.

As soon as I updated v1.2.7 to the clients, I began to follow the logs from the server to see what they give out. The board with mjson v1.2.5 still sometimes outed `\uXXXX` on negative float values ​​and only `\uXXXX`. Boards with v1.2.7 did not out `\uXXXX` in negative float numbers, but much more often they gave out `\uXXXX` with additional garbage at the beginning of payload, which was formed by the `mjson_printf()` function, for example:
`"@\u0002�\u0005{\"deviceId\":"further correct information..."`. `@\u0002�\u0005` is the garbage.
Most boards on the server, which had a very old mjson did not out anything like that. Today I downloaded again the logs to see. Now all boards with mjson v1.2.x gave garbage at the beginning of the message. Once this garbage appeared at the end of the message. I can't explain the reason for this garbage, maybe there is an bug somewhere on my side (for example, incorrect synchronization of FreeRTOS threads), maybe on the mjson side, but this result is acceptable for me, since json parsers discard this garbage. Therefore, I did not get hung up on this issue more

**Comment by cpq** [comment] 2021-09-16 18:44
@DmiKarasev Thank you!

Not sure that you need to replace float to double in your firmware. Just a call to mjson API needs a cast, that's all.

Trying to reproduce garbage with some random generation, like below - but no luck.. If you can find out what number triggers a problem, that'd be very helpful!

```c
static void test_double(void) {
  int i, j;
  char b1[100], b2[100];
  srand((unsigned) time(0));
  for (i = 0; i < 999999; i++) {
    double r = (double) rand() / RAND_MAX;
    if (r > 0.5) r = -r;
    r *= 17.0;
    mjson_snprintf(b1, sizeof(b1), "%g", r);
    snprintf(b2, sizeof(b2), "%g", r);
    for (j = 0; b1[j] != '\0'; j++)
      if (b1[j] != '.' && b1[j] != '-' && !isxdigit(b1[j]))
        printf("%.8f\n%s\n%s\n\n", r, b2, b1);
    // if (strcmp(b1, b2) != 0) printf("[%lu %lu] %s %s\n", n1, ++n2, b1, b2);
    // if (strcmp(b1, b2) != 0) printf("%.8f\n%s\n%s\n\n", r, b2, b1);
    // ASSERT(strcmp(b1, b2) == 0);
  }
}
```

**Comment by cpq** [comment] 2021-09-16 18:50
offtopic :  I'd recommend to try https://vcon.io : hook up any ESP32 board to your STM32 board (only SWD wires would be enough), flash ESP32 fw and configure it - and you'll get OTA instantly.  ESP32 acts as a remote programmer and network bridge to any external MQTT server. That way you cannot brick your device with a bad firmware, even if you flash a bad one.

**Comment by cpq** [comment] 2021-12-09 11:52
Closing this due to the lack of further comments.
Feel free to reopen if there is more data available.

**Closed by cpq** 2021-12-09 11:52 UTC
